name: cd
on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            - name: Check out the code
              uses: actions/checkout@v4
              
            - name: Setup Go toolchain
              uses: actions/setup-go@v4
              with:
                go-version: '1.20'

            - name: Build app
              run: ./scripts/buildprod.sh && go build .